import Foundation

enum ClipboardCaptureDecision: Equatable, Sendable {
  case capture
  case ignoreConfidential
  case ignoreTransient
  case ignoreGenerated
}

enum ClipboardCapturePolicy {
  static let sourceType = "org.nspasteboard.source"
  static let autoGeneratedType = "org.nspasteboard.AutoGeneratedType"

  private static let confidentialTypes: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "com.agilebits.onepassword",
    "net.antelle.keeweb",
  ]

  private static let transientTypes: Set<String> = [
    "org.nspasteboard.TransientType",
    "de.petermaurer.TransientPasteboardType",
    "com.typeit4me.clipping",
    "Pasteboard generator type",
  ]

  private static let generatedTypes: Set<String> = [
    autoGeneratedType
  ]

  static func decision(for types: some Sequence<String>) -> ClipboardCaptureDecision {
    let types = Set(types)
    if !types.isDisjoint(with: confidentialTypes) { return .ignoreConfidential }
    if !types.isDisjoint(with: transientTypes) { return .ignoreTransient }
    if !types.isDisjoint(with: generatedTypes) { return .ignoreGenerated }
    return .capture
  }
}

struct OneShotCaptureGuard: Sendable {
  private(set) var isArmed = false

  mutating func arm() {
    isArmed = true
  }

  mutating func cancel() {
    isArmed = false
  }

  mutating func consume(ifEligible isEligible: Bool = true) -> Bool {
    guard isArmed, isEligible else { return false }
    isArmed = false
    return true
  }
}
